reverting 2023.2 upgrade because of vitis issue; improved linux compatibility with xsct/xsct.bat check

diff --git a/firmware/build b/firmware/build
--- a/firmware/build
+++ b/firmware/build
@@ -1,10 +1,15 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
+
+unset xsct_cmd
+command -v xsct &>/dev/null && export xsct_cmd="xsct"
+command -v xsct.bat &>/dev/null && export xsct_cmd="xsct.bat"
+[ -z ${xsct_cmd+x} ] && echo "ERROR: can't locate xsct.bat or xsct" && exit 1
 
 start=$(date +%s)
 cd vitis || exit
-xsct.bat ../build-vitis.tcl
+$xsct_cmd ../build-vitis.tcl
 end=$(date +%s)
-elapsed=$((end-start))
+elapsed=$((end - start))
 
 echo "============================================="
 echo "build firmware project took $elapsed seconds"
diff --git a/firmware/create b/firmware/create
--- a/firmware/create
+++ b/firmware/create
@@ -1,12 +1,18 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 [ -d "./vitis" ] && echo "directory vitis already exists - skipping firmware project creation" && exit
+
+unset xsct_cmd
+command -v xsct &> /dev/null && export xsct_cmd="xsct"
+command -v xsct.bat &> /dev/null && export xsct_cmd="xsct.bat"
+[ -z ${xsct_cmd+x} ] && echo "ERROR: can't locate xsct.bat or xsct" && exit 1
+
 start=$(date +%s)
 mkdir vitis
 cd vitis || exit
-xsct.bat ../create-vitis.tcl
+$xsct_cmd ../create-vitis.tcl
 end=$(date +%s)
-elapsed=$((end-start))
+elapsed=$((end - start))
 
 echo "============================================="
 echo "create firmware project took $elapsed seconds"
